user_configuration: true
is_production: true
max_buf_space_mb: 1024
concurrent_amount_per_website: 3   # 下载同一 website 的下载项的并发量

# GitHub API ，如果不了解，可删除
# GitHub_Api_Token:
#   X-GitHub-Api-Version: "2022-11-28"
#   Authorization: "Bearer github_pat_11AXxxxxTWJA1"

## 下面不填的话，删除即可
default_category: Uncategorized
default_image: https://ib.ahfei.blog/imagesbed/picture_has_been_chewed_up_by_cat_vfly2.webp
default_website: https://github.com/AhFeil/updatefetch

post2RSS:
  ip_or_domain: rss.vfly2.com
  port: 80
  username: xxx
  password: xxx
  source_name: uf_severe_log
